//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.08 at 02:14:33 PM UTC 
//


package com.examples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "fusionsync")
public class Fusionsync {

    @XmlAttribute(name = "huburn", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String huburn;
    @XmlAttribute(name = "projecturn", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String projecturn;
    @XmlAttribute(name = "f3durn", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String f3Durn;
    @XmlAttribute(name = "pcbguid", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pcbguid;
    @XmlAttribute(name = "lastsyncedchangeguid", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lastsyncedchangeguid;
    @XmlAttribute(name = "lastpulledtime", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lastpulledtime;

    /**
     * Gets the value of the huburn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHuburn() {
        return huburn;
    }

    /**
     * Sets the value of the huburn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHuburn(String value) {
        this.huburn = value;
    }

    /**
     * Gets the value of the projecturn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjecturn() {
        return projecturn;
    }

    /**
     * Sets the value of the projecturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjecturn(String value) {
        this.projecturn = value;
    }

    /**
     * Gets the value of the f3Durn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getF3Durn() {
        return f3Durn;
    }

    /**
     * Sets the value of the f3Durn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setF3Durn(String value) {
        this.f3Durn = value;
    }

    /**
     * Gets the value of the pcbguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbguid() {
        return pcbguid;
    }

    /**
     * Sets the value of the pcbguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbguid(String value) {
        this.pcbguid = value;
    }

    /**
     * Gets the value of the lastsyncedchangeguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastsyncedchangeguid() {
        return lastsyncedchangeguid;
    }

    /**
     * Sets the value of the lastsyncedchangeguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastsyncedchangeguid(String value) {
        this.lastsyncedchangeguid = value;
    }

    /**
     * Gets the value of the lastpulledtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastpulledtime() {
        return lastpulledtime;
    }

    /**
     * Sets the value of the lastpulledtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastpulledtime(String value) {
        this.lastpulledtime = value;
    }

}
