//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.08 at 01:58:07 PM UTC 
//


package com.examples;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schematicGroup",
    "boardGroup"
})
@XmlRootElement(name = "groups")
public class Groups {

    @XmlElement(name = "schematic_group")
    protected List<SchematicGroup> schematicGroup;
    @XmlElement(name = "board_group")
    protected List<BoardGroup> boardGroup;

    /**
     * Gets the value of the schematicGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schematicGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchematicGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchematicGroup }
     * 
     * 
     */
    public List<SchematicGroup> getSchematicGroup() {
        if (schematicGroup == null) {
            schematicGroup = new ArrayList<SchematicGroup>();
        }
        return this.schematicGroup;
    }

    /**
     * Gets the value of the boardGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the boardGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBoardGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BoardGroup }
     * 
     * 
     */
    public List<BoardGroup> getBoardGroup() {
        if (boardGroup == null) {
            boardGroup = new ArrayList<BoardGroup>();
        }
        return this.boardGroup;
    }

}
