//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.08 at 12:43:50 PM UTC 
//


package com.examples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "packages",
    "packages3D",
    "symbols",
    "devicesets"
})
@XmlRootElement(name = "library")
public class Library {

    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "urn")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String urn;
    protected Description description;
    protected Packages packages;
    @XmlElement(name = "packages3d")
    protected Packages3D packages3D;
    protected Symbols symbols;
    protected Devicesets devicesets;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the urn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrn() {
        if (urn == null) {
            return "";
        } else {
            return urn;
        }
    }

    /**
     * Sets the value of the urn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrn(String value) {
        this.urn = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the packages property.
     * 
     * @return
     *     possible object is
     *     {@link Packages }
     *     
     */
    public Packages getPackages() {
        return packages;
    }

    /**
     * Sets the value of the packages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packages }
     *     
     */
    public void setPackages(Packages value) {
        this.packages = value;
    }

    /**
     * Gets the value of the packages3D property.
     * 
     * @return
     *     possible object is
     *     {@link Packages3D }
     *     
     */
    public Packages3D getPackages3D() {
        return packages3D;
    }

    /**
     * Sets the value of the packages3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packages3D }
     *     
     */
    public void setPackages3D(Packages3D value) {
        this.packages3D = value;
    }

    /**
     * Gets the value of the symbols property.
     * 
     * @return
     *     possible object is
     *     {@link Symbols }
     *     
     */
    public Symbols getSymbols() {
        return symbols;
    }

    /**
     * Sets the value of the symbols property.
     * 
     * @param value
     *     allowed object is
     *     {@link Symbols }
     *     
     */
    public void setSymbols(Symbols value) {
        this.symbols = value;
    }

    /**
     * Gets the value of the devicesets property.
     * 
     * @return
     *     possible object is
     *     {@link Devicesets }
     *     
     */
    public Devicesets getDevicesets() {
        return devicesets;
    }

    /**
     * Sets the value of the devicesets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Devicesets }
     *     
     */
    public void setDevicesets(Devicesets value) {
        this.devicesets = value;
    }

}
