//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.17 at 02:42:09 PM UTC 
//


package com.examples;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "package3Dinstance"
})
@XmlRootElement(name = "package3dinstances")
public class Package3Dinstances {

    @XmlElement(name = "package3dinstance")
    protected List<Package3Dinstance> package3Dinstance;

    /**
     * Gets the value of the package3Dinstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the package3Dinstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackage3Dinstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Package3Dinstance }
     * 
     * 
     */
    public List<Package3Dinstance> getPackage3Dinstance() {
        if (package3Dinstance == null) {
            package3Dinstance = new ArrayList<Package3Dinstance>();
        }
        return this.package3Dinstance;
    }

}
