//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.03 at 07:45:01 PM UTC 
//


package com.examples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "pinmap")
public class Pinmap {

    @XmlAttribute(name = "gate", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String gate;
    @XmlAttribute(name = "pin", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pin;
    @XmlAttribute(name = "pinorder", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pinorder;

    /**
     * Gets the value of the gate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGate() {
        return gate;
    }

    /**
     * Sets the value of the gate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGate(String value) {
        this.gate = value;
    }

    /**
     * Gets the value of the pin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPin() {
        return pin;
    }

    /**
     * Sets the value of the pin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPin(String value) {
        this.pin = value;
    }

    /**
     * Gets the value of the pinorder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinorder() {
        return pinorder;
    }

    /**
     * Sets the value of the pinorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinorder(String value) {
        this.pinorder = value;
    }

}
