name: Convert DTD

on:
  push:
      
permissions:
    contents: write
    
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '8'

      - continue-on-error: true
        shell: cmd
        run: md generatedsrc

      - shell: cmd
        run: xjc -dtd -d generatedsrc -p com.examples "eagle.dtd"

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      
      # - name: Archive Release
      #   uses: thedoctor0/zip-release@master
      #   with:
      #     type: 'zip'
      #     path: ${{ github.event.repository.name }}*
      #     filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
          
      # - name: Release prebuilt
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
      #     allowUpdates: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
